#!/usr/bin/env bash
#
# chassis-entrypoint — container init. Stages the env file, seeds the agent
# home if empty, renders models.json + tools-public.json + cron, then execs
# cron. --reload re-runs only the tools-public.json + cron rendering.
# --oneshot <agent> [task] runs init (everything but cron), then execs
# run-agent once and exits with its status — for scheduler-driven,
# scale-to-zero deployments (one container per run, no internal cron).

set -euo pipefail

ENV_SRC=/run/secrets/chassis.env
ENV_DST=/etc/chassis/.env
TOOLS_SRC=/mnt/protected/tools/tools.json
TOOLS_PUBLIC=/etc/chassis/tools-public.json
AGENT_HOME="${AGENT_HOME:-/home/agent}"
export AGENT_HOME
SEED_MARKER="$AGENT_HOME/.chassis-seeded"
TEMPLATE_DIR=/usr/local/share/chassis/agent-template
CRON_FILE=/etc/cron.d/chassis
LOG_DIR=/var/log/chassis

reload_only=0
oneshot=0
oneshot_agent=""
oneshot_task=""
case "${1:-}" in
    --reload)
        reload_only=1
        ;;
    --oneshot)
        oneshot=1
        oneshot_agent="${2:-}"
        oneshot_task="${3:-}"
        if [[ -z "$oneshot_agent" ]]; then
            echo "entrypoint: --oneshot needs <agent> [task]" >&2
            exit 2
        fi
        ;;
esac

render_tools_public() {
    install -d -m 755 /etc/chassis
    python3 - "$TOOLS_SRC" "$TOOLS_PUBLIC" <<'PY'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
m = json.load(open(src))
public = {
    "tools": [
        {
            "name":         t["name"],
            "description":  t.get("description", ""),
            "args_schema":  t.get("args_schema", {"type": "object"}),
        }
        for t in m.get("tools", [])
    ]
}
json.dump(public, open(dst, "w"), indent=2)
PY
    chmod 644 "$TOOLS_PUBLIC"
    local n
    n=$(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))["tools"]))' "$TOOLS_PUBLIC")
    echo "entrypoint: tools-public.json rendered ($n tools)"
}

render_cron() {
    local count=0
    local lines=""
    # Tasks live at /home/agent/<agent>/<task>/cron — matching the path
    # run-agent and the harness extension use for INSTRUCTIONS.md. Globs skip
    # dotfiles, so .pi/.bashrc/.chassis-seeded don't masquerade as agents.
    for cron_file in "$AGENT_HOME"/*/*/cron; do
        [[ -f "$cron_file" ]] || continue
        local task_dir agent_name task_name schedule
        task_dir="$(dirname "$cron_file")"
        task_name="$(basename "$task_dir")"
        agent_name="$(basename "$(dirname "$task_dir")")"
        schedule="$(grep -v '^[[:space:]]*#' "$cron_file" | grep -v '^[[:space:]]*$' | head -1 || true)"
        [[ -z "$schedule" ]] && continue
        lines+="$schedule agent /usr/local/bin/run-agent $agent_name $task_name >> $LOG_DIR/cron.log 2>&1"$'\n'
        count=$((count+1))
    done
    {
        echo "# Generated by chassis-entrypoint at $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit by hand."
        echo "SHELL=/bin/bash"
        echo "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        echo "MAILTO=\"\""
        echo
        if (( count == 0 )); then
            echo "# (no scheduled tasks)"
        else
            printf '%s' "$lines"
        fi
        echo
    } > "$CRON_FILE"
    chmod 644 "$CRON_FILE"
    chown root:root "$CRON_FILE"
    echo "entrypoint: cron rendered ($count tasks)"
}

# --- Reload path ------------------------------------------------------------
if (( reload_only )); then
    render_tools_public
    render_cron
    echo "entrypoint: reloaded at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    exit 0
fi

# --- Full init --------------------------------------------------------------

# 1. agent user
if ! id agent >/dev/null 2>&1; then
    useradd -m -u 2000 -s /bin/bash agent
fi
echo "entrypoint: agent user OK"

# 2. .env -> tmpfs
install -d -m 755 /etc/chassis
if [[ -f "$ENV_SRC" ]]; then
    install -m 600 -o root -g root "$ENV_SRC" "$ENV_DST"
else
    install -m 600 -o root -g root /dev/null "$ENV_DST"
fi
echo "entrypoint: env staged"

# 3. $AGENT_HOME ownership + virgin-volume seed
# When AGENT_HOME is per-user (e.g. /home/agent/users/<id>) it may not yet
# exist on a fresh shared mount; create it first so the chown/chmod succeed.
install -d -o agent -g agent -m 755 "$AGENT_HOME"
chown agent:agent "$AGENT_HOME"
chmod 755 "$AGENT_HOME"
# Agents live directly at /home/agent/<name>/, so we can't detect "virgin
# volume" by emptiness — the home always has .pi, .bashrc, etc. The marker
# file is the source of truth instead.
if [[ -d "$TEMPLATE_DIR" ]] && [[ ! -f "$SEED_MARKER" ]]; then
    for entry in "$TEMPLATE_DIR"/*; do
        [[ -e "$entry" ]] || continue
        name="$(basename "$entry")"
        cp -r "$entry" "$AGENT_HOME/"
        chown -R agent:agent "$AGENT_HOME/$name"
    done
    install -m 644 -o agent -g agent /dev/null "$SEED_MARKER"
    echo "entrypoint: seeded $AGENT_HOME from template"
fi

# Log dir (named volume; first mount is root:root)
mkdir -p "$LOG_DIR/agents"
chown -R agent:agent "$LOG_DIR"
touch "$LOG_DIR/cron.log"
chown agent:agent "$LOG_DIR/cron.log"

# 4. models.json
install -d -m 755 -o agent -g agent "$AGENT_HOME/.pi/agent"
# LLM_API_KEY from env (e.g. compose `environment:` for tests) wins;
# otherwise pull it out of the staged .env without sourcing the whole file
# (avoids bash interpreting arbitrary tool secret values). Defaults to
# "unused" downstream for local endpoints (vLLM, ollama) that ignore it.
if [[ -z "${LLM_API_KEY:-}" && -s "$ENV_DST" ]]; then
    LLM_API_KEY="$(grep -E '^LLM_API_KEY=' "$ENV_DST" | tail -n1 | cut -d= -f2-)"
    LLM_API_KEY="${LLM_API_KEY%\"}"; LLM_API_KEY="${LLM_API_KEY#\"}"
    LLM_API_KEY="${LLM_API_KEY%\'}"; LLM_API_KEY="${LLM_API_KEY#\'}"
fi
export LLM_API_KEY
python3 - "$AGENT_HOME/.pi/agent/models.json" <<'PY'
import json, os, sys
cfg = {"providers": {"llm": {
    "baseUrl": os.environ.get("LLM_BASE_URL", "http://llm:8000/v1"),
    "api":     os.environ.get("LLM_API_KIND", "openai-completions"),
    "apiKey":  os.environ.get("LLM_API_KEY") or "unused",
    "compat":  {"supportsDeveloperRole": False, "supportsReasoningEffort": False},
    "headers": {
        "X-Chassis-Agent": "CHASSIS_AGENT",
        "X-Chassis-Task":  "!printf %s \"${CHASSIS_TASK:-interactive}\"",
    },
    "models": [{
        "id":            os.environ.get("LLM_MODEL_ID", ""),
        "contextWindow": int(os.environ.get("LLM_CONTEXT_WINDOW", "8192")),
        "maxTokens":     int(os.environ.get("LLM_MAX_TOKENS", "4096")),
    }],
}}}
json.dump(cfg, open(sys.argv[1], "w"), indent=2)
PY
chown agent:agent "$AGENT_HOME/.pi/agent/models.json"
chmod 600 "$AGENT_HOME/.pi/agent/models.json"
echo "entrypoint: models.json rendered"

# 5. tools-public.json
render_tools_public

# 6. cron — skipped in one-shot mode, where scheduling is external: a
#    scheduler launches one container per run, so there's no internal cron.
if (( oneshot )); then
    # Bind this home to its subscriber if a provisioner hasn't already. The
    # agent reads $AGENT_HOME/user.json for its id (not CHASSIS_USER), so the
    # binding survives the tool dispatcher's env scrub. Idempotent: a warm,
    # already-provisioned volume keeps its existing user.json untouched.
    if [[ -n "${CHASSIS_USER:-}" && ! -f "$AGENT_HOME/user.json" ]]; then
        python3 - "$CHASSIS_USER" > "$AGENT_HOME/user.json" <<'PY'
import json, sys
json.dump({"id": sys.argv[1]}, sys.stdout)
PY
        chown agent:agent "$AGENT_HOME/user.json"
        chmod 600 "$AGENT_HOME/user.json"
        echo "entrypoint: bound home to user '$CHASSIS_USER'"
    fi
    # Ready marker first (parity with the daemon path), then hand off. The
    # container's exit status is the task's, so a scheduler can tell a clean
    # run from a failure.
    : > /run/chassis-ready
    run_cmd=(/usr/local/bin/run-agent "$oneshot_agent")
    [[ -n "$oneshot_task" ]] && run_cmd+=("$oneshot_task")
    echo "entrypoint: one-shot, exec'ing run-agent $oneshot_agent ${oneshot_task:-(interactive)}"
    exec tini -- "${run_cmd[@]}"
fi

render_cron

# 7. hand off
# Drop a ready marker so tests/operators have a single file to poll on, after
# every render step has run. /run is tmpfs, so this never persists across boots.
: > /run/chassis-ready
echo "entrypoint: ready, exec'ing cron"
exec tini -- cron -f
